[colors.normal]
black = "#000000"
blue = "#56A8F5"
cyan = "#2AACB8"
green = "#6AAB73"
red = "#F75464"
white = "#BCBEC4"
yellow = "#FFC66D"

[colors.primary]
background = "#1E1F22"
foreground = "#BCBEC4"

[colors.cursor]
cursor = "#BCBEC4"
text = "#1E1F22"

######################

[font]
size = 8

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Hai Cao"

[terminal]
